name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"
    
    - name: Install dependencies
      run: |
        swift package resolve
    
    - name: Build
      run: |
        swift build -v
    
    - name: Run tests
      run: |
        swift test -v
  
  lint:
    name: SwiftLint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
  
  xcode-build:
    name: Xcode Build
    runs-on: macos-latest
    needs: [build, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install dependencies
      run: |
        swift package resolve
    
    - name: Build for iOS
      run: |
        xcodebuild -scheme ScreenTimeApp -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' build
    
    # Archive step would be here in a real deployment pipeline
    # - name: Archive
    #   run: |
    #     xcodebuild -scheme ScreenTimeApp -archivePath ScreenTimeApp.xcarchive archive
    
    # TestFlight upload would be here in a real deployment pipeline
    # - name: Upload to TestFlight
    #   run: |
    #     xcrun altool --upload-app -f ScreenTimeApp.ipa -t ios -u ${{ secrets.APPLE_ID }} -p ${{ secrets.APPLE_APP_PASSWORD }}
